#!/bin/sh
PG_HOST=$POSTGRES_HOST
PG_PORT=$POSTGRES_PORT
PG_USER=$GUSER
PG_PASS=$USER_PASSWORD
PG_DB=$USER_DB

PG_HOST=$PG_HOST PG_PORT=$PG_PORT PG_USER=$PG_USER PG_PASS=$PG_PASS PG_DB=$PG_DB node /opt/user/index.js
